# Generated by Django 3.1.2 on 2020-10-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0007_auto_20201023_2129'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Издательство')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес')),
                ('city', models.CharField(blank=True, max_length=60, null=True, verbose_name='Город')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна')),
                ('publication_date', models.DateField()),
                ('books', models.ManyToManyField(to='hello_world.Seris', verbose_name='Название книги')),
            ],
        ),
        migrations.DeleteModel(
            name='Publishing',
        ),
    ]
