# Generated by Django 3.1.2 on 2020-10-25 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20201023_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aut_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Имя автора')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='books',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
        migrations.CreateModel(
            name='Seris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название книги')),
                ('number_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.aut_book', verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gener', models.CharField(max_length=50, verbose_name='Жанр')),
                ('coin', models.IntegerField(verbose_name='Цена книги')),
                ('publication_date', models.DateField(verbose_name='Дата')),
                ('number_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.seris', verbose_name='Название книги')),
            ],
        ),
    ]
