# Generated by Django 3.1.2 on 2020-11-03 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20201101_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='number',
            new_name='number_book',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='publish',
        ),
        migrations.RemoveField(
            model_name='book',
            name='address',
        ),
        migrations.RemoveField(
            model_name='book',
            name='city',
        ),
    ]
