# Generated by Django 3.1.2 on 2020-11-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20201103_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='aut_book',
            field=models.CharField(default='Tolkin', max_length=50, verbose_name='Имя автора'),
            preserve_default=False,
        ),
    ]
