# Generated by Django 3.1.2 on 2020-11-11 14:04

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20201108_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pic',
            field=models.ImageField(default='file.txt', upload_to=books.models.upload, verbose_name='Book picture'),
            preserve_default=False,
        ),
    ]
