# Generated by Django 3.1.2 on 2020-10-22 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aut_book',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Биография автора'),
        ),
        migrations.CreateModel(
            name='Seris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Серия книги')),
                ('number_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello_world.aut_book')),
            ],
        ),
    ]
