# Generated by Django 3.1.2 on 2020-10-22 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0002_auto_20201022_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aut_book',
            name='author',
            field=models.CharField(max_length=50, verbose_name='Авторы книг'),
        ),
        migrations.AlterField(
            model_name='aut_book',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Биография автора'),
        ),
        migrations.AlterField(
            model_name='seris',
            name='number',
            field=models.CharField(max_length=50, verbose_name='Серия книги'),
        ),
        migrations.AlterField(
            model_name='seris',
            name='number_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello_world.aut_book', verbose_name='Автор'),
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Издательство')),
                ('books', models.ManyToManyField(to='hello_world.Seris', verbose_name='Книги')),
            ],
        ),
    ]
