# Generated by Django 3.1.2 on 2020-10-22 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0003_auto_20201022_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='books',
            field=models.ManyToManyField(to='hello_world.Seris', verbose_name='Название книги'),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gener_tab', models.CharField(max_length=50, verbose_name='Жанр')),
                ('number_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello_world.public', verbose_name='Книги')),
            ],
        ),
    ]
