# Generated by Django 3.1.2 on 2020-10-23 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0004_auto_20201022_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Издательство')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес')),
                ('city', models.CharField(blank=True, max_length=60, null=True, verbose_name='Город')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна')),
            ],
        ),
        migrations.AddField(
            model_name='aut_book',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='aut_book',
            name='author',
            field=models.CharField(max_length=50, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='number_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello_world.seris', verbose_name='Книги'),
        ),
        migrations.AlterField(
            model_name='seris',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Серия книги'),
        ),
        migrations.DeleteModel(
            name='Public',
        ),
        migrations.AddField(
            model_name='publish',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='hello_world.Seris', verbose_name='Название книги'),
        ),
    ]
