# Generated by Django 3.1.2 on 2020-10-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0005_auto_20201023_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aut_book',
            name='author',
            field=models.CharField(max_length=50, verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='aut_book',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Фамилия автора'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='books',
            field=models.ManyToManyField(to='hello_world.Seris', verbose_name='Название книги'),
        ),
    ]
