# Generated by Django 3.1.2 on 2020-10-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0006_auto_20201023_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='publish',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя автора'),
        ),
        migrations.AddField(
            model_name='publish',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Биография автора'),
        ),
        migrations.AddField(
            model_name='publish',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Фамилия автора'),
        ),
        migrations.AlterField(
            model_name='aut_book',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Биография автора'),
        ),
    ]
