# Generated by Django 3.1.2 on 2020-10-25 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0007_auto_20201023_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='number_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello_world.seris', verbose_name='Название книги'),
        ),
    ]
