# Generated by Django 3.1.2 on 2020-11-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0009_auto_20201101_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aut_book',
            name='author',
            field=models.CharField(default=None, max_length=50, verbose_name='Имя автора'),
        ),
    ]
