# Generated by Django 3.1.2 on 2020-11-01 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0010_auto_20201101_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publish',
            name='author',
        ),
        migrations.RemoveField(
            model_name='publish',
            name='books',
        ),
        migrations.RemoveField(
            model_name='publish',
            name='description',
        ),
        migrations.RemoveField(
            model_name='publish',
            name='last_name',
        ),
    ]
