# Generated by Django 3.1.2 on 2020-11-17 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_pic'),
        ('orders', '0002_bookincart'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookincart',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='books_in_carts', to='books.book'),
            preserve_default=False,
        ),
    ]
